workflows:
  android-workflow:
    name: Android Workflow

    environment:
      flutter: stable

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release --android-skip-build-dependency-validation

    artifacts:
      - build/app/outputs/**/*.apk
